export enum EmailTemplateTypes {
  ORDER_RECEIPT = 'ORDER_RECEIPT',
  ORDER_STATUS_CANCELLED = 'ORDER_STATUS_CANCELLED',
  ORDER_STATUS_DELIVERED = 'ORDER_STATUS_DELIVERED',
  ORDER_STATUS_FAILED_PAYMENT = 'ORDER_STATUS_FAILED_PAYMENT',
  ORDER_STATUS_ON_DELIVERY = 'ORDER_STATUS_ON_DELIVERY',
  ORDER_STATUS_PAID = 'ORDER_STATUS_PAID',
  ORDER_STATUS_PENDING_PAYMENT = 'ORDER_STATUS_PENDING_PAYMENT',
  ORDER_STATUS_SENT = 'ORDER_STATUS_SENT',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY',
}
