export enum OrderStatusToEmailType {
  PENDING_PAYMENT = 'ORDER_STATUS_PENDING_PAYMENT',
  FAILED_PAYMENT = 'ORDER_STATUS_FAILED_PAYMENT',
  PAID = 'ORDER_STATUS_PAID',
  SENT = 'ORDER_STATUS_SENT',
  ON_DELIVERY = 'ORDER_STATUS_ON_DELIVERY',
  DELIVERED = 'ORDER_STATUS_DELIVERED',
  CANCELLED = 'ORDER_STATUS_CANCELLED',
}
